-- Booting the script 

local Fluent = loadstring(game:HttpGet("https://github.com/dawid-scripts/Fluent/releases/latest/download/main.lua"))()

-- First window (Main window)

local Window = Fluent:CreateWindow({
    Title = "Mato GUI " .. Fluent.Version,
    SubTitle = "by Mato",
    TabWidth = 160,
    Size = UDim2.fromOffset(580, 460),
    Acrylic = true, -- The blur may be detectable, setting this to false disables blur entirely
    Theme = "Dark",
    MinimizeKey = Enum.KeyCode.LeftControl -- Used when theres no MinimizeKeybind
})

-- Notification

Fluent:Notify({
        Title = "Execution",
        Content = "Script Executed Succesfully",
        SubContent = "SubContent", -- Optional
        Duration = 7 -- Set to nil to make the notification not disappear
})

-- Fluent provides Lucide Icons, they are optional
local Tabs = {
    Main = Window:AddTab({ Title = "Main", Icon = "" }),
    Settings = Window:AddTab({ Title = "Settings", Icon = "settings" })
}

local SaveManager = loadstring(game:HttpGet("https://raw.githubusercontent.com/dawid-scripts/Fluent/master/Addons/SaveManager.lua"))()
local InterfaceManager = loadstring(game:HttpGet("https://raw.githubusercontent.com/dawid-scripts/Fluent/master/Addons/InterfaceManager.lua"))()

SaveManager:SetLibrary(Fluent)
InterfaceManager:SetLibrary(Fluent)

InterfaceManager:BuildInterfaceSection(Tabs.Settings)
SaveManager:BuildConfigSection(Tabs.Settings)

Tabs.Main:AddButton({
    Title = "Anti-Ban",
    Description = "Protects you from Bans",
    Callback = function()
        Fluent:Notify({
        Title = "Anti Ban",
        Content = "Anti Ban Enabled",
        SubContent = "ExecutionContent", -- Optional
        Duration = 5 -- Set to nil to make the notification not disappear
})

    end
})

Tabs.Main:AddButton({
    Title = "Auto Fish",
    Description = "Starts Auto Fish",
    Callback = function()
        -- Auto Fishing Script for "Be a Silly Seal" on Roblox
-- Script generated by TurtleSpy, made by Intrer#0421
-- Auto function created by Ww1avi

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local FishingEvents = ReplicatedStorage.Scripts.Fishing.Events

-- Function to automate the fishing process
local function autoFish()
    -- Deploy the bob at the specified fishing spot
    FishingEvents.DeployBob:FireServer(workspace.FishingSpots.FishingSpot, CFrame.new(205.743484, 132.25, 269.160004, 1, 0, 0, 0, -4.37113883e-08, -1, 0, 1, -4.37113883e-08))
    
    -- Wait for a short duration to simulate waiting for a fish to bite
    wait(2)
    
    -- Finish the catch
    FishingEvents.FinishCatch:FireServer(true)
    
    -- Wait for a short duration to simulate the end of the fishing process
    wait(1)
    
    -- Finish fishing
    FishingEvents.FinishFishing:FireServer()
    
    -- Perform the shake action
    FishingEvents.DoShake:FireServer()
end

-- Loop the auto fishing function to continuously fish
while true do
    autoFish()
    -- Wait for a short duration before starting the next fishing cycle
    wait(5)
end
    end
})
